// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: peer.proto

package cliapi

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetPeerRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SetPeerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetPeerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SetPeerRequestMultiError,
// or nil if none found.
func (m *SetPeerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetPeerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Connect

	if len(errors) > 0 {
		return SetPeerRequestMultiError(errors)
	}

	return nil
}

// SetPeerRequestMultiError is an error wrapping multiple validation errors
// returned by SetPeerRequest.ValidateAll() if the designated constraints
// aren't met.
type SetPeerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetPeerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetPeerRequestMultiError) AllErrors() []error { return m }

// SetPeerRequestValidationError is the validation error returned by
// SetPeerRequest.Validate if the designated constraints aren't met.
type SetPeerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetPeerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetPeerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetPeerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetPeerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetPeerRequestValidationError) ErrorName() string { return "SetPeerRequestValidationError" }

// Error satisfies the builtin error interface
func (e SetPeerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetPeerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetPeerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetPeerRequestValidationError{}

// Validate checks the field values on RemovePeerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RemovePeerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemovePeerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemovePeerRequestMultiError, or nil if none found.
func (m *RemovePeerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemovePeerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RemovePeerRequestMultiError(errors)
	}

	return nil
}

// RemovePeerRequestMultiError is an error wrapping multiple validation errors
// returned by RemovePeerRequest.ValidateAll() if the designated constraints
// aren't met.
type RemovePeerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemovePeerRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemovePeerRequestMultiError) AllErrors() []error { return m }

// RemovePeerRequestValidationError is the validation error returned by
// RemovePeerRequest.Validate if the designated constraints aren't met.
type RemovePeerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePeerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePeerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePeerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePeerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePeerRequestValidationError) ErrorName() string {
	return "RemovePeerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePeerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePeerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePeerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePeerRequestValidationError{}

// Validate checks the field values on PeerResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PeerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PeerResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PeerResponseMultiError, or
// nil if none found.
func (m *PeerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PeerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Connected

	if len(errors) > 0 {
		return PeerResponseMultiError(errors)
	}

	return nil
}

// PeerResponseMultiError is an error wrapping multiple validation errors
// returned by PeerResponse.ValidateAll() if the designated constraints aren't met.
type PeerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PeerResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PeerResponseMultiError) AllErrors() []error { return m }

// PeerResponseValidationError is the validation error returned by
// PeerResponse.Validate if the designated constraints aren't met.
type PeerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PeerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PeerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PeerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PeerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PeerResponseValidationError) ErrorName() string { return "PeerResponseValidationError" }

// Error satisfies the builtin error interface
func (e PeerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPeerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PeerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PeerResponseValidationError{}

// Validate checks the field values on PeerList with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PeerList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PeerList with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PeerListMultiError, or nil
// if none found.
func (m *PeerList) ValidateAll() error {
	return m.validate(true)
}

func (m *PeerList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPeers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PeerListValidationError{
						field:  fmt.Sprintf("Peers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PeerListValidationError{
						field:  fmt.Sprintf("Peers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PeerListValidationError{
					field:  fmt.Sprintf("Peers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PeerListMultiError(errors)
	}

	return nil
}

// PeerListMultiError is an error wrapping multiple validation errors returned
// by PeerList.ValidateAll() if the designated constraints aren't met.
type PeerListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PeerListMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PeerListMultiError) AllErrors() []error { return m }

// PeerListValidationError is the validation error returned by
// PeerList.Validate if the designated constraints aren't met.
type PeerListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PeerListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PeerListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PeerListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PeerListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PeerListValidationError) ErrorName() string { return "PeerListValidationError" }

// Error satisfies the builtin error interface
func (e PeerListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPeerList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PeerListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PeerListValidationError{}
